AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SqsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/sqs-handler/
      Description: Lambda para processar mensagens SQS e enviar callback para Step Functions
      MemorySize: 128
      Timeout: 3
      Handler: bootstrap  # Handler para Quarkus Native
      Runtime: provided.al2
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          DYNAMODB_TABLE: human-task-control
          # Descomente se quiser usar LocalStack.
          # AWS_ENDPOINT_URL: http://localhost:4566
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      # Removido RecursiveLoop por não ser suportado.
      # Removido SnapStart pois só se aplica a Java (Quarkus nativo não usa SnapStart).
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

            - Effect: Allow
              Action:
                - sqs:*
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"

            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/human-task-control"

            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:CallbackPatternStateMachine"
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue1.Arn
            BatchSize: 10
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto

  SQSQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SQSQueue1
      SqsManagedSseEnabled: true

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSQueue1
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt SQSQueue1.Arn

  CallbackPatternStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/statemachines/callback-pattern.asl.json
      # Ajuste a Role para a sua conta/ambiente
      Role: arn:aws:iam::123456789012:role/service-role/StepFunctions-Local
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
              Resource: !GetAtt SQSQueue1.Arn
      Events:
        HttpEvent:
          Type: Api
          Properties:
            Path: /start
            Method: POST
